// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FollowedCommunityPostView } from "./FollowedCommunityPostView";

export interface GetFollowedCommunityPostsResponse {
  posts: Array<FollowedCommunityPostView>;
}
